name: quizzy_land
description: Quiz app using flutter

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_timer_countdown: ^1.0.5
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/google_fonts/
